/*
 *   This file is a part of the SteamWar software.
 *
 *   Copyright (C) 2024 SteamWar.de-Serverteam
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Affero General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Affero General Public License for more details.
 *
 *   You should have received a copy of the GNU Affero General Public License
 *   along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package de.steamwar.core;

import org.bukkit.Material;
import org.bukkit.Particle;
import org.bukkit.enchantments.Enchantment;
import org.bukkit.entity.EntityType;
import org.bukkit.inventory.InventoryView;

public class TrickyTrialsWrapper21 implements TrickyTrialsWrapper {
    @Override
    public EntityType getTntEntityType() {
        return EntityType.TNT;
    }

    @Override
    public Enchantment getUnbreakingEnchantment() {
        return Enchantment.UNBREAKING;
    }

    @Override
    public Material getTurtleScute() {
        return Material.TURTLE_SCUTE;
    }

    @Override
    public String getInventoryTitle(InventoryView view) {
        return view.getTitle();
    }
}
