/*
 *   This file is a part of the SteamWar software.
 *
 *   Copyright (C) 2025 SteamWar.de-Serverteam
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Affero General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Affero General Public License for more details.
 *
 *   You should have received a copy of the GNU Affero General Public License
 *   along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package de.steamwar.bausystem.world;

import de.steamwar.sql.SchematicData;
import de.steamwar.sql.SchematicNode;
import de.steamwar.sql.SteamwarUser;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.player.PlayerJoinEvent;
import org.bukkit.event.player.PlayerQuitEvent;

public class ClipboardListener implements Listener {

    private static final String CLIPBOARD_SCHEMNAME = "//copy";

    @EventHandler
    public void onLogin(PlayerJoinEvent e) {
        try {
            SchematicNode schematic = SchematicNode.getSchematicNode(SteamwarUser.get(e.getPlayer().getUniqueId()).getId(), CLIPBOARD_SCHEMNAME, (Integer) null);
            if (schematic != null) {
                new SchematicData(schematic).loadToPlayer(e.getPlayer());
            }
        } catch (Exception ex) {
            // ignore cause players do all kind of stuff with schematics.... like massively oversized schems
        }
    }

    @EventHandler
    public void onLogout(PlayerQuitEvent e) {
        SchematicNode schematic = SchematicNode.getSchematicNode(SteamwarUser.get(e.getPlayer().getUniqueId()).getId(), CLIPBOARD_SCHEMNAME, (Integer) null);
        boolean newSchem = false;
        if (schematic == null) {
            schematic = SchematicNode.createSchematic(SteamwarUser.get(e.getPlayer().getUniqueId()).getId(), CLIPBOARD_SCHEMNAME, null);
            newSchem = true;
        }

        try {
            SchematicData.saveFromPlayer(e.getPlayer(), schematic);
        } catch (Exception ex) {
            if (newSchem) {
                schematic.delete();
            }
        }
    }
}
