/*
 *   This file is a part of the SteamWar software.
 *
 *   Copyright (C) 2025 SteamWar.de-Serverteam
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Affero General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Affero General Public License for more details.
 *
 *   You should have received a copy of the GNU Affero General Public License
 *   along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package de.steamwar.bausystem.features.loader.elements.impl;

import de.steamwar.bausystem.features.loader.elements.LoaderInteractionElement;
import de.steamwar.bausystem.features.loader.elements.LoaderSettingsEnum;
import de.steamwar.inventory.SWItem;
import org.bukkit.Location;
import org.bukkit.Material;
import org.bukkit.block.data.type.Switch;
import org.bukkit.entity.Player;

import java.util.function.Consumer;

public class LoaderLever extends LoaderInteractionElement<LoaderLever.LeverSettingsEnum> {

    public LoaderLever(Location location) {
        super(location, LeverSettingsEnum.INTERACT, LeverSettingsEnum.NOOP, LeverSettingsEnum.values());
    }

    public enum LeverSettingsEnum implements LoaderSettingsEnum<Switch, LoaderLever, LeverSettingsEnum> {

        NOOP {
            @Override
            public int getPos() {
                return 2;
            }

            @Override
            public SWItem menu(Player player, LoaderLever parent, int power, long ticks) {
                return new SWItem(Material.STRUCTURE_VOID, translateItemName("LOADER_BUTTON_SWITCH", "LOADER_INTERACTION_NOOP", player));
            }

            @Override
            public void execute(Location location, Switch blockData, LoaderLever parent, int power, long ticks, Consumer<Long> delay) {
            }
        },

        INTERACT {
            @Override
            public int getPos() {
                return 3;
            }

            @Override
            public SWItem menu(Player player, LoaderLever parent, int power, long ticks) {
                return new SWItem(Material.STICK, translateItemName("LOADER_BUTTON_SWITCH", "LOADER_INTERACTION_INTERACT", player));
            }

            @Override
            public void execute(Location location, Switch blockData, LoaderLever parent, int power, long ticks, Consumer<Long> delay) {
                blockData.setPowered(!blockData.isPowered());
                parent.update(blockData);
            }
        },

        POWER_OFF {
            @Override
            public int getPos() {
                return 5;
            }

            @Override
            public SWItem menu(Player player, LoaderLever parent, int power, long ticks) {
                return new SWItem(Material.LEVER, translateItemName("LOADER_BUTTON_SWITCH", "LOADER_INTERACTION_INACTIVE", player));
            }

            @Override
            public void execute(Location location, Switch blockData, LoaderLever parent, int power, long ticks, Consumer<Long> delay) {
                blockData.setPowered(false);
                parent.update(blockData);
            }
        },

        POWER_ON {
            @Override
            public int getPos() {
                return 6;
            }

            @Override
            public SWItem menu(Player player, LoaderLever parent, int power, long ticks) {
                return new SWItem(Material.LEVER, translateItemName("LOADER_BUTTON_SWITCH", "LOADER_INTERACTION_ACTIVE", player));
            }

            @Override
            public void execute(Location location, Switch blockData, LoaderLever parent, int power, long ticks, Consumer<Long> delay) {
                blockData.setPowered(true);
            }
        }
    }

    @Override
    public SWItem menu(Player player) {
        return new SWItem(Material.LEVER, translateItemName("LOADER_BUTTON_LECTERN", player));
    }

    @Override
    public boolean checkBlockInWorld() {
        return location.getBlock().getType() == Material.LEVER;
    }
}
