/*
 *   This file is a part of the SteamWar software.
 *
 *   Copyright (C) 2025 SteamWar.de-Serverteam
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Affero General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Affero General Public License for more details.
 *
 *   You should have received a copy of the GNU Affero General Public License
 *   along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package de.steamwar.bausystem.features.region.items;

import de.steamwar.bausystem.BauSystem;
import de.steamwar.bausystem.Permission;
import de.steamwar.bausystem.SWUtils;
import de.steamwar.bausystem.features.region.ResetCommand;
import de.steamwar.bausystem.linkage.BauGuiItem;
import de.steamwar.inventory.SWItem;
import de.steamwar.inventory.SchematicSelector;
import de.steamwar.linkage.Linked;
import de.steamwar.linkage.LinkedInstance;
import org.bukkit.Material;
import org.bukkit.entity.Player;
import org.bukkit.event.inventory.ClickType;
import org.bukkit.inventory.ItemStack;

@Linked
public class ResetBauGuiItem extends BauGuiItem {

    @LinkedInstance
    public ResetCommand resetCommand;

    public ResetBauGuiItem() {
        super(6);
    }

    @Override
    public ItemStack getItem(Player player) {
        return SWUtils.setCustomModelData(new SWItem(Material.HEAVY_WEIGHTED_PRESSURE_PLATE, BauSystem.MESSAGE.parse("REGION_ITEM_RESET", player)), 1).getItemStack();
    }

    @Override
    public boolean click(ClickType click, Player p) {
        if (click == ClickType.LEFT) {
            p.closeInventory();
            resetCommand.genericResetCommand(p);
        } else {
            SchematicSelector selector = new SchematicSelector(p, SchematicSelector.selectSchematic(), node -> {
                p.closeInventory();
                resetCommand.schematicResetCommand(p, node);
            });
            selector.open();
        }
        return false;
    }

    @Override
    public Permission permission() {
        return Permission.BUILD;
    }
}
