/*
 *   This file is a part of the SteamWar software.
 *
 *   Copyright (C) 2025 SteamWar.de-Serverteam
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Affero General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Affero General Public License for more details.
 *
 *   You should have received a copy of the GNU Affero General Public License
 *   along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package de.steamwar.bausystem.features.util.items;

import de.steamwar.bausystem.BauSystem;
import de.steamwar.bausystem.Permission;
import de.steamwar.bausystem.linkage.BauGuiItem;
import de.steamwar.inventory.SWItem;
import de.steamwar.inventory.SWListInv;
import de.steamwar.linkage.Linked;
import org.bukkit.Bukkit;
import org.bukkit.Material;
import org.bukkit.entity.Player;
import org.bukkit.event.inventory.ClickType;
import org.bukkit.inventory.ItemStack;

import java.util.UUID;

@Linked
public class TeleportBauGuiItem extends BauGuiItem {

    public TeleportBauGuiItem() {
        super(10);
    }

    @Override
    public ItemStack getItem(Player player) {
        return new SWItem(Material.ENDER_PEARL, BauSystem.MESSAGE.parse("OTHER_ITEMS_TELEPORT_NAME", player)).getItemStack();
    }

    @Override
    public boolean click(ClickType click, Player p) {
        p.closeInventory();
        SWListInv<UUID> inv = new SWListInv<>(p, BauSystem.MESSAGE.parse("OTHER_ITEMS_TELEPORT_GUI_NAME", p), SWListInv.createPlayerList(p.getUniqueId()), (clickType, o) -> {
            Player t = Bukkit.getPlayer(o);
            if (t == null) {
                BauSystem.MESSAGE.send("OTHER_ITEMS_TELEPORT_PLAYER_OFFLINE", p);
            } else {
                p.performCommand("tp " + t.getName());
            }
        });
        inv.open();
        return false;
    }

    @Override
    public Permission permission() {
        return Permission.MEMBER;
    }
}
