/* 
    This file is a part of the SteamWar software.
    
    Copyright (C) 2020  SteamWar.de-Serverteam

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

package de.steamwar.misslewars.countdowns;

import de.steamwar.misslewars.Config;
import de.steamwar.misslewars.FightState;
import de.steamwar.misslewars.MissileWars;
import de.steamwar.misslewars.StateDependent;
import org.bukkit.Bukkit;
import org.bukkit.scheduler.BukkitTask;

import java.util.EnumSet;

public class WaitingCountdown extends StateDependent {

	private BukkitTask task;

	public WaitingCountdown() {
		super(EnumSet.of(FightState.WAITING));
	}

	@Override
	public void enable() {
		task = Bukkit.getScheduler().runTaskLater(MissileWars.getPlugin(), () -> {
			if(Bukkit.getOnlinePlayers().isEmpty())
				Bukkit.shutdown();
		}, Config.WaitingTime);
	}

	@Override
	public void disable() {
		if(task != null && !task.isCancelled())
			task.cancel();
	}
}
