/*
 *   This file is a part of the SteamWar software.
 *
 *   Copyright (C) 2025 SteamWar.de-Serverteam
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Affero General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Affero General Public License for more details.
 *
 *   You should have received a copy of the GNU Affero General Public License
 *   along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package de.steamwar.towerrun;

import de.steamwar.command.SWCommand;
import de.steamwar.linkage.AbstractLinker;
import de.steamwar.linkage.LinkedInstance;
import de.steamwar.linkage.SpigotLinker;
import de.steamwar.message.Message;
import de.steamwar.towerrun.config.WorldConfig;
import de.steamwar.towerrun.countdowns.GameCountdown;
import de.steamwar.towerrun.generator.TowerGenerator;
import lombok.Getter;
import org.bukkit.Bukkit;
import org.bukkit.plugin.java.JavaPlugin;
import org.bukkit.plugin.java.annotation.dependency.Dependency;
import org.bukkit.plugin.java.annotation.plugin.ApiVersion;
import org.bukkit.plugin.java.annotation.plugin.Description;
import org.bukkit.plugin.java.annotation.plugin.Plugin;
import org.bukkit.plugin.java.annotation.plugin.author.Author;

@Plugin(name = "TowerRun", version = "1.0.0")
@Dependency("SpigotCore")
@Author("YoyoNow")
@Author("Chaoscaot")
@Description("SteamWar TowerRun Plugin")
@ApiVersion(ApiVersion.Target.v1_19)
public class TowerRun extends JavaPlugin {

    @Getter
    private static TowerRun instance;

    @Getter
    private static Message message;

    @Getter
    private static TowerGenerator towerGenerator = null;

    @Getter
    @LinkedInstance
    private static GameCountdown gameCountdown;


    @Override
    public void onEnable() {
        instance = this;
        message = new Message("TowerRun", getClassLoader());

        if (WorldConfig.TOWER_GENERATOR_CONFIG != null) {
            towerGenerator = new TowerGenerator(WorldConfig.TOWER_GENERATOR_CONFIG);
        }

        SpigotLinker spigotLinker = new SpigotLinker(this, message) {
            @Override
            protected void linkObject(Object any) {
                if (any instanceof SWCommand) {
                    ((SWCommand) any).setMessage(message);
                }
            }
        };
        try {
            spigotLinker.link();
        } catch (AbstractLinker.LinkException e) {
            e.printStackTrace();
            Bukkit.shutdown();
            return;
        }

        Bukkit.getScheduler().runTaskTimer(this, new FightInfoPacketSender(), 20, 20);
    }
}
