/*
 *   This file is a part of the SteamWar software.
 *
 *   Copyright (C) 2025 SteamWar.de-Serverteam
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Affero General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Affero General Public License for more details.
 *
 *   You should have received a copy of the GNU Affero General Public License
 *   along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package de.steamwar.bausystem.commands;

import de.steamwar.bausystem.BauSystem;
import de.steamwar.command.SWCommand;
import org.bukkit.entity.Player;
import org.bukkit.potion.PotionEffect;
import org.bukkit.potion.PotionEffectType;

public class CommandGills extends SWCommand {

    public CommandGills() {
        super("watervision", "wv");
    }

    @Register(help = true)
    public void genericHelp(Player p, String... args) {
        p.sendMessage("§8/§ewatervision §8- §7Toggle WaterBreathing");
    }

    @Register
    public void genericCommand(Player p) {
        toggleGills(p);
    }

    public static void toggleGills(Player player) {
        if (player.hasPotionEffect(PotionEffectType.WATER_BREATHING)) {
            player.sendMessage(BauSystem.PREFIX + "Wassersicht deaktiviert");
            player.removePotionEffect(PotionEffectType.WATER_BREATHING);
            return;
        }
        player.addPotionEffect(new PotionEffect(PotionEffectType.WATER_BREATHING, 1000000, 255, false, false));
        player.sendMessage(BauSystem.PREFIX + "Wassersicht aktiviert");
    }
}
