/*
 *   This file is a part of the SteamWar software.
 *
 *   Copyright (C) 2025 SteamWar.de-Serverteam
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Affero General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Affero General Public License for more details.
 *
 *   You should have received a copy of the GNU Affero General Public License
 *   along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package de.steamwar.misslewars.listener.special;

import de.steamwar.linkage.Linked;
import de.steamwar.misslewars.Config;
import de.steamwar.misslewars.FightState;
import de.steamwar.misslewars.listener.BasicListener;
import org.bukkit.Material;
import org.bukkit.block.Block;
import org.bukkit.event.EventHandler;
import org.bukkit.event.block.BlockPhysicsEvent;

import java.util.EnumSet;

@Linked
public class BarrierListener extends BasicListener {

    public BarrierListener() {
        super(EnumSet.allOf(FightState.class));
    }

    private int middle = Config.ArenaMinZ + (Config.ArenaMaxZ - Config.ArenaMinZ) / 2;

    @EventHandler
    public void onBlockPhysics(BlockPhysicsEvent event) {
        if (!Config.Barrier) return;
        Block block = event.getBlock();
        if (block.getZ() > middle - 10 && block.getZ() < middle + 10) {
            switch (block.getType()) {
                case SLIME_BLOCK:
                case HONEY_BLOCK:
                case TNT:
                    block.setType(Material.AIR);
                    break;
                default:
                    break;
            }
        }
    }
}
