/*
 *   This file is a part of the SteamWar software.
 *
 *   Copyright (C) 2025 SteamWar.de-Serverteam
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Affero General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Affero General Public License for more details.
 *
 *   You should have received a copy of the GNU Affero General Public License
 *   along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package de.steamwar.lobby.particle.elements;

import de.steamwar.lobby.LobbySystem;
import de.steamwar.lobby.particle.ParticleElement;
import de.steamwar.lobby.particle.ParticleTickData;
import org.bukkit.Bukkit;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.player.PlayerQuitEvent;

import java.util.HashMap;
import java.util.Map;

public class Delayed extends DelegatingParticleElement {

    private DelayedData delayedData = new DelayedData();
    private int interval;

    private static class DelayedData implements Listener {
        private Map<Player, Integer> data = new HashMap<>();

        @EventHandler(ignoreCancelled = true)
        public void onPlayerQuit(PlayerQuitEvent event) {
            data.remove(event.getPlayer());
        }
    }

    public Delayed(ParticleElement particleElement, int interval) {
        super(particleElement);
        Bukkit.getPluginManager().registerEvents(delayedData, LobbySystem.getInstance());
        this.interval = interval;
        if (interval <= 0) {
            throw new IllegalArgumentException("Interval must be greater than 0");
        }
    }

    @Override
    public String attribute() {
        return null;
    }

    @Override
    public void tick(ParticleTickData particleTickData) {
        int currentNumber = delayedData.data.getOrDefault(particleTickData.getPlayer(), 0) % interval;
        delayedData.data.put(particleTickData.getPlayer(), currentNumber + 1);
        if (currentNumber != 0) {
            return;
        }
        particleElement.tick(particleTickData);
    }
}
