/*
 * This file is a part of the SteamWar software.
 *
 * Copyright (C) 2021  SteamWar.de-Serverteam
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package de.steamwar.bausystem.features.util.items;

import de.steamwar.bausystem.BauSystem;
import de.steamwar.bausystem.Permission;
import de.steamwar.bausystem.linkage.specific.BauGuiItem;
import de.steamwar.inventory.SWItem;
import de.steamwar.linkage.Linked;
import org.bukkit.Material;
import org.bukkit.entity.Player;
import org.bukkit.event.inventory.ClickType;
import org.bukkit.inventory.ItemStack;

@Linked
public class DebugstickBauGuiItem extends BauGuiItem {

    public DebugstickBauGuiItem() {
        super(12);
    }

    @Override
    public ItemStack getItem(Player player) {
        return new SWItem(Material.DEBUG_STICK, BauSystem.MESSAGE.parse("DEBUG_STICK_NAME", player)).getItemStack();
    }

    @Override
    public boolean click(ClickType click, Player p) {
        p.closeInventory();
        p.performCommand("debugstick");
        return false;
    }

    @Override
    public Permission permission() {
        return Permission.BUILD;
    }
}
