/*
 *   This file is a part of the SteamWar software.
 *
 *   Copyright (C) 2025 SteamWar.de-Serverteam
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Affero General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Affero General Public License for more details.
 *
 *   You should have received a copy of the GNU Affero General Public License
 *   along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package de.steamwar.bausystem.region;

import de.steamwar.bausystem.region.fixed.FixedGlobalRegion;
import de.steamwar.bausystem.region.fixed.loader.PrototypeLoader;
import de.steamwar.bausystem.region.fixed.loader.RegionLoader;
import lombok.NonNull;
import org.bukkit.Bukkit;
import org.bukkit.Location;

import java.util.HashMap;
import java.util.Map;
import java.util.Optional;
import java.util.UUID;
import java.util.stream.Stream;

public class FixedRegionSystem implements RegionSystem {

    private static final Map<UUID, Region> REGION_MAP = new HashMap<>();

    public static void addRegion(Region region) {
        REGION_MAP.put(region.getID(), region);
    }

    @Override
    public void load() {
        PrototypeLoader.load();
        RegionLoader.load();
    }

    @Override
    public void save() {
    }

    @Override
    public @NonNull Location getWorldSpawn() {
        Location spawnLocation = Bukkit.getWorlds().get(0).getSpawnLocation();
        Location spawnPoint = Bukkit.getWorlds().get(0).getHighestBlockAt(spawnLocation).getLocation();
        return spawnPoint.add(0.5, 1, 0.5);
    }

    @Override
    public Region getGlobalRegion() {
        return FixedGlobalRegion.INSTANCE;
    }

    @Override
    public Region get(Location location) {
        return REGION_MAP.values().stream()
                .filter(region -> region.getArea().inRegion(location, false))
                .findFirst()
                .orElse(FixedGlobalRegion.INSTANCE);
    }

    @Override
    public Optional<Region> getRegion(@NonNull UUID id) {
        return Optional.ofNullable(REGION_MAP.get(id));
    }

    @Override
    public Stream<Region> getRegions() {
        return REGION_MAP.values().stream();
    }
}
