/*
 * This file is a part of the SteamWar software.
 *
 * Copyright (C) 2022  SteamWar.de-Serverteam
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package de.steamwar.bausystem.features.world;

import de.steamwar.bausystem.Permission;
import de.steamwar.bausystem.config.BauServer;
import de.steamwar.command.SWCommand;
import de.steamwar.command.TypeValidator;
import de.steamwar.linkage.Linked;
import de.steamwar.linkage.LinkedInstance;
import org.bukkit.Bukkit;
import org.bukkit.entity.Player;

@Linked
public class KickallCommand extends SWCommand {

    @LinkedInstance
    public BauServer bauServer;

    public KickallCommand() {
        super("kickall");
    }

    @Register(description = "KICKALL_HELP")
    public void genericCommand(Player player) {
        if(!Permission.OWNER.hasPermission(player)) return;

        Bukkit.getOnlinePlayers().forEach(p -> {
            if (!bauServer.getOwner().equals(p.getUniqueId())) p.kickPlayer("");
        });
    }
}
