/*
 *   This file is a part of the SteamWar software.
 *
 *   Copyright (C) 2025 SteamWar.de-Serverteam
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Affero General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Affero General Public License for more details.
 *
 *   You should have received a copy of the GNU Affero General Public License
 *   along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package de.steamwar.towerrun.winconditions;

import de.steamwar.towerrun.game.TowerRunGame;
import de.steamwar.towerrun.game.TowerRunPlayer;
import org.bukkit.GameMode;
import org.bukkit.event.EventHandler;
import org.bukkit.event.EventPriority;
import org.bukkit.event.entity.PlayerDeathEvent;
import org.bukkit.event.player.PlayerQuitEvent;

public class LastRemainingWincondition extends WinCondition {

    public LastRemainingWincondition() {
        super("LAST_REMAINING");
    }

    @EventHandler
    public void onPlayerDeath(PlayerDeathEvent event) {
        TowerRunPlayer tPlayer = TowerRunPlayer.get(event.getEntity());
        TowerRunGame.PLAYERS_ALIVE.remove(tPlayer);
        TowerRunGame.PLAYERS_ESCAPED.remove(tPlayer);
        tPlayer.player().setGameMode(GameMode.SPECTATOR);
        if (TowerRunGame.PLAYERS_ALIVE.size() == 1 && TowerRunGame.PLAYERS_ESCAPED.isEmpty()) {
            TowerRunGame.win(TowerRunGame.PLAYERS_ALIVE.get(0));
        }
    }

    @EventHandler(priority = EventPriority.LOW)
    public void onPlayerQuit(PlayerQuitEvent event) {
        TowerRunPlayer tPlayer = TowerRunPlayer.get(event.getPlayer());
        if (TowerRunGame.isAlive(tPlayer)) {
            TowerRunGame.PLAYERS_ALIVE.remove(tPlayer);
            TowerRunGame.PLAYERS_ESCAPED.remove(tPlayer);
            if (TowerRunGame.PLAYERS_ALIVE.size() == 1 && TowerRunGame.PLAYERS_ESCAPED.isEmpty()) {
                TowerRunGame.win(TowerRunGame.PLAYERS_ALIVE.get(0));
            }
        }
    }
}
