/*
 *   This file is a part of the SteamWar software.
 *
 *   Copyright (C) 2025 SteamWar.de-Serverteam
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Affero General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Affero General Public License for more details.
 *
 *   You should have received a copy of the GNU Affero General Public License
 *   along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package de.steamwar.bausystem.features.bau;

import de.steamwar.bausystem.BauSystem;
import de.steamwar.bausystem.Permission;
import de.steamwar.bausystem.config.BauServer;
import de.steamwar.bausystem.linkage.BauGuiItem;
import de.steamwar.bausystem.region.FlagOptional;
import de.steamwar.bausystem.region.Region;
import de.steamwar.bausystem.region.flags.Flag;
import de.steamwar.inventory.SWItem;
import de.steamwar.linkage.Linked;
import de.steamwar.sql.SteamwarUser;
import org.bukkit.Material;
import org.bukkit.entity.Player;
import org.bukkit.event.inventory.ClickType;
import org.bukkit.inventory.ItemStack;

import java.util.ArrayList;
import java.util.List;

@Linked
public class BauInfoBauGuiItem extends BauGuiItem {

    public BauInfoBauGuiItem() {
        super(7);
    }

    @Override
    public ItemStack getItem(Player player) {
        SWItem itemStack;
        if (!player.getName().endsWith("⍇")) {
            itemStack = SWItem.getPlayerSkull(SteamwarUser.get(BauServer.getInstance().getOwner()).getUserName());
        } else {
            itemStack = new SWItem(Material.PLAYER_HEAD, "");
        }
        itemStack.setName(BauSystem.MESSAGE.parse("BAU_INFO_ITEM_NAME", player));
        Region region = Region.getRegion(player.getLocation());
        List<String> stringList = new ArrayList<>();
        for (Flag flag : Flag.getFlags()) {
            if (!region.getFlags().has(flag).isApplicable()) continue;
            FlagOptional<?> value = region.getFlags().get(flag);
            if (value.isPresent()) {
                stringList.add(BauSystem.MESSAGE.parse("BAU_INFO_ITEM_LORE_" + flag.name(), player, BauSystem.MESSAGE.parse(value.getWithDefault().getChatValue(), player)));
            }
        }
        itemStack.setLore(stringList);
        return itemStack.getItemStack();
    }

    @Override
    public boolean click(ClickType click, Player p) {
        return false;
    }

    @Override
    public Permission permission() {
        return Permission.MEMBER;
    }
}
