/*
 *   This file is a part of the SteamWar software.
 *
 *   Copyright (C) 2025 SteamWar.de-Serverteam
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Affero General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Affero General Public License for more details.
 *
 *   You should have received a copy of the GNU Affero General Public License
 *   along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package de.steamwar.bausystem.features.slaves.laufbau.boundingboxes;

import de.steamwar.bausystem.features.slaves.laufbau.BlockBoundingBox;
import de.steamwar.bausystem.features.slaves.laufbau.BoundingBoxLoader;
import de.steamwar.bausystem.features.slaves.laufbau.Cuboid;
import de.steamwar.linkage.Linked;
import org.bukkit.Material;
import org.bukkit.block.BlockFace;
import org.bukkit.block.data.type.Fence;

import java.util.ArrayList;
import java.util.List;

import static de.steamwar.bausystem.features.slaves.laufbau.LaufbauUtils.createItem;
import static de.steamwar.bausystem.features.slaves.laufbau.LaufbauUtils.pixelCuboid;

@Linked
public class IronBarBoundingBox implements BoundingBoxLoader {

    @Override
    public void load() {
        for (int nx = 0; nx < 2; nx++) {
            for (int nz = 0; nz < 2; nz++) {
                for (int px = 0; px < 2; px++) {
                    for (int pz = 0; pz < 2; pz++) {
                        Fence fence = (Fence) Material.IRON_BARS.createBlockData();
                        List<String> lore = new ArrayList<>();
                        List<Cuboid> cuboidList = new ArrayList<>();
                        cuboidList.add(pixelCuboid(7, 0, 7, 2, 16, 2));
                        if (nz == 1) {
                            lore.add("LAUFBAU_CONNECTION_NORTH");
                            fence.setFace(BlockFace.NORTH, true);
                            cuboidList.add(pixelCuboid(7, 0, 0, 2, 16, 7));
                        }
                        if (pz == 1) {
                            lore.add("LAUFBAU_CONNECTION_SOUTH");
                            fence.setFace(BlockFace.SOUTH, true);
                            cuboidList.add(pixelCuboid(7, 0, 9, 2, 16, 7));
                        }
                        if (nx == 1) {
                            lore.add("LAUFBAU_CONNECTION_WEST");
                            fence.setFace(BlockFace.WEST, true);
                            cuboidList.add(pixelCuboid(0, 0, 7, 7, 16, 2));
                        }
                        if (px == 1) {
                            lore.add("LAUFBAU_CONNECTION_EAST");
                            fence.setFace(BlockFace.EAST, true);
                            cuboidList.add(pixelCuboid(9, 0, 7, 7, 16, 2));
                        }
                        new BlockBoundingBox(fence, cuboidList, createItem("LAUFBAU_BLOCK_IRON_BARS", Material.IRON_BARS, lore.toArray(new String[0])));
                    }
                }
            }
        }
    }
}
