/*
 *   This file is a part of the SteamWar software.
 *
 *   Copyright (C) 2025 SteamWar.de-Serverteam
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Affero General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Affero General Public License for more details.
 *
 *   You should have received a copy of the GNU Affero General Public License
 *   along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package de.steamwar.bausystem.features.loader.elements.impl;

import de.steamwar.bausystem.features.loader.elements.LoaderInteractionElement;
import de.steamwar.bausystem.features.loader.elements.LoaderSettingsEnum;
import de.steamwar.inventory.SWItem;
import org.bukkit.Location;
import org.bukkit.Material;
import org.bukkit.block.data.Openable;
import org.bukkit.entity.Player;

import java.util.function.Consumer;

public class LoaderOpenable extends LoaderInteractionElement<LoaderOpenable.OpenableSettingsEnum> {

    private String name;
    private Material material;

    public LoaderOpenable(Location location, String name, Material material) {
        super(location, OpenableSettingsEnum.INTERACT, OpenableSettingsEnum.NOOP, OpenableSettingsEnum.values());
        this.name = name;
        this.material = material;
    }

    public enum OpenableSettingsEnum implements LoaderSettingsEnum<Openable, LoaderOpenable, OpenableSettingsEnum> {

        NOOP {
            @Override
            public int getPos() {
                return 2;
            }

            @Override
            public SWItem menu(Player player, LoaderOpenable parent, int power, long ticks) {
                return new SWItem(Material.STRUCTURE_VOID, translateItemName(parent.name, "LOADER_INTERACTION_NOOP", player));
            }

            @Override
            public void execute(Location location, Openable blockData, LoaderOpenable parent, int power, long ticks, Consumer<Long> delay) {
            }
        },

        INTERACT {
            @Override
            public int getPos() {
                return 3;
            }

            @Override
            public SWItem menu(Player player, LoaderOpenable parent, int power, long ticks) {
                return new SWItem(Material.STICK, translateItemName(parent.name, "LOADER_INTERACTION_INTERACT", player));
            }

            @Override
            public void execute(Location location, Openable blockData, LoaderOpenable parent, int power, long ticks, Consumer<Long> delay) {
                blockData.setOpen(!blockData.isOpen());
                parent.update(blockData);
            }
        },

        CLOSED {
            @Override
            public int getPos() {
                return 5;
            }

            @Override
            public SWItem menu(Player player, LoaderOpenable parent, int power, long ticks) {
                return new SWItem(parent.material, translateItemName(parent.name, "LOADER_INTERACTION_CLOSED", player));
            }

            @Override
            public void execute(Location location, Openable blockData, LoaderOpenable parent, int power, long ticks, Consumer<Long> delay) {
                blockData.setOpen(false);
                parent.update(blockData);
            }
        },

        OPEN {
            @Override
            public int getPos() {
                return 6;
            }

            @Override
            public SWItem menu(Player player, LoaderOpenable parent, int power, long ticks) {
                return new SWItem(parent.material, translateItemName(parent.name, "LOADER_INTERACTION_OPEN", player));
            }

            @Override
            public void execute(Location location, Openable blockData, LoaderOpenable parent, int power, long ticks, Consumer<Long> delay) {
                blockData.setOpen(true);
                parent.update(blockData);
            }
        }
    }

    @Override
    public SWItem menu(Player player) {
        return new SWItem(material, translateItemName(name, player));
    }

    @Override
    public boolean checkBlockInWorld() {
        return location.getBlock().getType() == material;
    }
}
